[versions]
kotlin = "2.1.0"
morphe-patcher = "1.0.0"       # Check https://github.com/MorpheApp/registry for latest
morphe-patches-library = "1.0.0"
gson = "2.11.0"
arsclib = "a28c6fb2a7"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
morphe-patches-library = { module = "app.morphe:patches-library", version.ref = "morphe-patches-library" }
arsclib = { module = "com.github.REAndroid:ARSCLib", version.ref = "arsclib" }

[plugins]
morphe-patcher = { id = "com.morphe.patcher", version.ref = "morphe-patcher" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
